# Generated by Django 6.0 on 2026-02-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="can_unpublish_product",
            field=models.BooleanField(
                default=False, verbose_name="Не разрешено отменить публикацию"
            ),
        ),
    ]
