# Generated by Django 6.0 on 2026-02-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_can_unpublish_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("can_unpublish_product", "Может отменить публикацию продукта")
                ],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
